# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploadDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonURL',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('URL', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=400)),
                ('uploadDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.UUIDField(default=uuid.uuid4)),
                ('comment', models.CharField(max_length=1000)),
                ('commentDate', models.DateTimeField(blank=True, null=True)),
                ('comparisonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Comparison')),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('ratingDate', models.DateTimeField(blank=True, null=True)),
                ('comparisonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Comparison')),
                ('pictureID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Picture')),
                ('raterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User')),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='ownerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
        ),
        migrations.AddField(
            model_name='comparisonurl',
            name='comparisonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Picture'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='pictureID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Picture'),
        ),
    ]
